# Generated by Django 5.2.17 on 2026-09-21 04:19

import core_api.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='OrgMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=16)),
                ('joined_at', models.DateTimeField()),
                ('org', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, to='platform_org.organization')),
            ],
            options={
                'db_table': 'org_membership',
                'constraints': [models.UniqueConstraint(fields=('org', 'user_id'), name='uq_org_membership_org_user')],
            },
        ),
    ]
