# Generated by Django 5.2.17 on 2026-09-21 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_org', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgmembership',
            name='org',
            field=models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='platform_org.organization'),
        ),
    ]
