# Generated by Django 5.2.17 on 2026-09-25 07:26

import core_api.utils
import django.db.models.deletion
import platform_org.models.org_invitation
from django.db import migrations, models


def make_first_members_owners(apps, schema_editor):
    """Orgs created before roles existed: whoever joined first (the
    creator) becomes the owner."""
    Organization = apps.get_model("platform_org", "Organization")
    OrgMembership = apps.get_model("platform_org", "OrgMembership")
    for org_id in Organization.objects.values_list("id", flat=True):
        first = OrgMembership.objects.filter(org_id=org_id).order_by("joined_at", "id").first()
        if first is not None:
            OrgMembership.objects.filter(pk=first.pk).update(role="owner")


class Migration(migrations.Migration):

    dependencies = [
        ('platform_org', '0002_alter_orgmembership_org'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgmembership',
            options={'verbose_name': 'member'},
        ),
        migrations.AddField(
            model_name='orgmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], db_default='member', default='member', max_length=16),
        ),
        migrations.CreateModel(
            name='OrgInvitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=16)),
                ('token', models.CharField(default=platform_org.models.org_invitation._new_token, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('invited_by', models.UUIDField()),
                ('expires_at', models.DateTimeField(default=platform_org.models.org_invitation._default_expiry)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='platform_org.organization')),
            ],
            options={
                'verbose_name': 'invitation',
                'db_table': 'org_invitation',
            },
        ),
        migrations.RunPython(make_first_members_owners, migrations.RunPython.noop),
    ]
